### ISSUE TITLE
No matching to unresolved names

### ISSUE THREAD

**Issue by Alectoria** [gustavobio/tpl#2]
Thanks Gustavo for your effort writing the tpl package. I have been using tpl.get() recently and got some unexptected results.

Example: Acaena saccaticupula (listed in the Plant List online)
     
     tpl.get("Acaena saccaticupula")

The note says "family not in APG" but the taxon is not a family and listed in the Plant list. Is it because it's an unresolved name? I am only intersted in matching and spell checking, so I would expect that at least the match comes up.

          id family    genus species infraspecific.rank infraspecific.epithet    authorship 
       taxonomic.status.in.tpl confidence.level source accepted.id name note      original.search
      rjp-12374      A Rosaceae   Acaena   saccaticupula        Bitter     L
      family not in APG Acaena saccaticupula

I also get a warning:

    Warning message:
    In `[<-.data.frame`(`*tmp*`, index, minus.notes, value = list(id = "rjp-12374",  :
      provided 22 variables to replace 13 variables.

**Comment by gustavobio** [comment]
Sorry, there was a problem I didn't spot in a tpldata commit. Should be fixed now, but I'm afraid you will have to reinstall the package. No changes were made to tpl to fix this, so reinstalling tpldata only will do. Please let me know if you have any more issues.

**Comment by Alectoria** [comment]
OK, I will try out the new tpldata version.
Thanks for looking into this!
