### ISSUE TITLE
Name parsing

### ISSUE THREAD

**Issue by Alectoria** [gustavobio/tpl#4]
I have been using tpl quite a lot and have noticed that it does not parse author names from taxonomic names. Would it be possible to include this feature? 

Name w/o author name (works)

    tpl.get("Poa annua",suggestion.distance = 0.8)

     id  family genus species infraspecific.rank infraspecific.epithet authorship taxonomic.status.in.tpl 
     confidence.level source accepted.id      name note original.search
    1 kew-435194 Poaceae   Poa   annua                                                  L.                Accepted                H
    1   WCSP             Poa annua            Poa annua

Name w/ author name (does not work)

     tpl.get("Poa annua L.",suggestion.distance = 0.8)

     id family genus species infraspecific.rank infraspecific.epithet authorship taxonomic.status.in.tpl   
     confidence.level source  accepted.id name  note original.search
      1 NA     NA    NA      NA                 NA                    NA         NA                      NA               NA     NA
      1          NA   NA not found    Poa annua L.

If the author name is not too long, I can get the correct name by lowering suggestion.distance but that does not always work well.

Thanks for the great package!

**Comment by gustavobio** [comment]
Hello

I've included a new argument `parse` in the last commit that calls the gbif name parser.

```
 tpl.get("Poa annua L.", parse = F)
  id family genus species infraspecific.rank infraspecific.epithet authorship taxonomic.status.in.tpl confidence.level
1 NA     NA    NA      NA                 NA                    NA         NA                      NA               NA
  source accepted.id name      note original.search
1     NA          NA   NA not found    Poa annua L.
```
```
tpl.get("Poa annua L.", parse = T)
          id  family genus species infraspecific.rank infraspecific.epithet authorship taxonomic.status.in.tpl
1 kew-435194 Poaceae   Poa   annua                                                  L.                Accepted
  confidence.level source accepted.id      name note original.search
1                H   WCSP             Poa annua         Poa annua L.
```

I haven't had the time to extensively test this, so please let me know if you find any errors.

Thank your for using the package!

**Comment by Alectoria** [comment]
Thanks, Gustavo! This is very helpful. I will test the new argument.

**Comment by gustavobio** [comment]
Hi @Alectoria, I'll push some tests this week and was wondering if the name parsing is working well. Did you find any errors? Thanks.

**Comment by Alectoria** [comment]
Hi @gustavo! I found it worked well at the species level. But I encountered difficulties at the subspecies/variety level. Here is an example with names I extracted from TPL online:

    test2 <-c("Poa annua L.",
          "Fumaria officinalis L.",
         "Stipa borysthenica Prokudin",
         "Helianthemum nummularium (L.) Mill.",
         "Stipa borysthenica subsp. germanica (Erdtman) Martinovský & Rausch",
         "Helianthemum nummularium subsp. glabrum (W.D.J.Koch) Wilczek",
         "Lathyrus alpestris subsp. friedrichsthalii (Griseb.) Bassler",
         "Festuca valesiaca var. asperrima (Hack.) E.B.Alexeev")

    tpl.get(test2,parse = T)

    tpl.get(test2,parse = T)
           id       family        genus     species infraspecific.rank infraspecific.epithet authorship
    1  kew-435194      Poaceae          Poa       annua                                                  L.
    2 kew-2815499 Papaveraceae      Fumaria officinalis                                                  L.
    3  kew-445508      Poaceae        Stipa     pennata                                                  L.
    4 kew-2842625    Cistaceae Helianthemum nummularium                                          (L.) Mill.
    5        <NA>         <NA>         <NA>        <NA>               <NA>                  <NA>       <NA>
    6        <NA>         <NA>         <NA>        <NA>               <NA>                  <NA>       <NA>
    7        <NA>         <NA>         <NA>        <NA>               <NA>                  <NA>       <NA>
    8        <NA>         <NA>         <NA>        <NA>               <NA>                  <NA>       <NA>
    taxonomic.status.in.tpl confidence.level           source accepted.id                     name
    1                Accepted                H             WCSP                            Poa annua
    2                Accepted                M WCSP (in review)                  Fumaria officinalis
    3                Accepted                L             WCSP                        Stipa pennata
    4                Accepted                M WCSP (in review)             Helianthemum nummularium
    5                    <NA>             <NA>             <NA>        <NA>                     <NA>
    6                    <NA>             <NA>             <NA>        <NA>                     <NA>
    7                    <NA>             <NA>             <NA>        <NA>                     <NA>
    8                    <NA>             <NA>             <NA>        <NA>                     <NA>
              note                                                    original.search
    1                                                                        Poa annua L.
    2                                                              Fumaria officinalis L.
    3 replaced synonym                                        Stipa borysthenica Prokudin
    4                                                 Helianthemum nummularium (L.) Mill.
    5        not found Stipa borysthenica subsp. germanica (Erdtman) Martinovský & Rausch
    6        not found       Helianthemum nummularium subsp. glabrum (W.D.J.Koch) Wilczek
    7        not found       Lathyrus alpestris subsp. friedrichsthalii (Griseb.) Bassler
    8        not found               Festuca valesiaca var. asperrima (Hack.) E.B.Alexeev

**Comment by gustavobio** [comment]
Hello @Alectoria, sorry for the late reply. Should be fixed now. Thank you again!

```coffee
> tpl.get(test2,parse = T)
            id       family        genus     species infraspecific.rank infraspecific.epithet           authorship taxonomic.status.in.tpl confidence.level           source accepted.id                                       name             note
1   kew-435194      Poaceae          Poa       annua                                                            L.                Accepted                H             WCSP                                              Poa annua                 
2  kew-2815499 Papaveraceae      Fumaria officinalis                                                            L.                Accepted                M WCSP (in review)                                    Fumaria officinalis                 
3   kew-445508      Poaceae        Stipa     pennata                                                            L.                Accepted                L             WCSP                                          Stipa pennata replaced synonym
4  kew-2842625    Cistaceae Helianthemum nummularium                                                    (L.) Mill.                Accepted                M WCSP (in review)                               Helianthemum nummularium                 
5   kew-445508      Poaceae        Stipa     pennata                                                            L.                Accepted                L             WCSP                                          Stipa pennata replaced synonym
6  kew-2898061    Cistaceae Helianthemum nummularium             subsp.               glabrum (W.D.J.Koch) Wilczek                Accepted                L WCSP (in review)                Helianthemum nummularium subsp. glabrum                 
7 tro-13044738     Fabaceae     Lathyrus   alpestris             subsp.      friedrichsthalii    (Griseb.) Bassler                Accepted                L              TRO             Lathyrus alpestris subsp. friedrichsthalii                 
8   kew-415130      Poaceae      Festuca  elwendiana                                                 Markgr.-Dann.                Accepted                H             WCSP                                     Festuca elwendiana replaced synonym
                                                     original.search
1                                                       Poa annua L.
2                                             Fumaria officinalis L.
3                                        Stipa borysthenica Prokudin
4                                Helianthemum nummularium (L.) Mill.
5 Stipa borysthenica subsp. germanica (Erdtman) Martinovský & Rausch
6       Helianthemum nummularium subsp. glabrum (W.D.J.Koch) Wilczek
7       Lathyrus alpestris subsp. friedrichsthalii (Griseb.) Bassler
8               Festuca valesiaca var. asperrima (Hack.) E.B.Alexeev
> 
```
